[package]
name = "secure-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aes.workspace = true
anyhow.workspace = true
cbc.workspace = true
connection-store = { path = "../connection-store" }
dirs.workspace = true
getrandom.workspace = true
parking_lot.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
